This is an example page for exercises to be done for the workshop. You would remove this page, replace it with your own and then adjust the `workshop.yaml` and `modules.yaml` file to list your pages instead.

In this example the pages which make up the core of the workshop content are placed in a sub directory. This is only done as a suggestion. You can place all pages at the same directory level if you wish.

Included below are some tests and examples of page formatting using AsciiDoc.

#### Standard code block

[source,bash]
----
echo "standard code block"
----

#### Click text to execute

[source,bash,role=execute-1]
----
echo "execute in terminal 1"
----

[source,bash,role=execute-2]
----
echo "execute in terminal 2"
----

[source,bash,role=execute]
----
echo "execute in terminal 1"
----

#### Click text to copy

[source,bash,role=copy]
----
echo "copy text to buffer"
----

#### Click text to copy (and edit)

[source,bash,role=copy-and-edit]
----
echo "copy text to buffer"
----

#### Interrupt command

[source,bash,role=execute]
----
sleep 3600
----

[source,bash,role=execute]
----
<ctrl-c>
----

#### Variable interpolation

base_url: %base_url%

console_url: %console_url%

terminal_url: %terminal_url%

slides_url: %slides_url%

username: %username%

project_namespace: %project_namespace%

cluster_subdomain: %cluster_subdomain%

image_registry: %image_registry%

#### Web site links

link:https://www.openshift.com[External]

link:%base_url%[Internal]

#### Console links

link:%console_url%[Projects]

link:%console_url%/overview/ns/%project_namespace%[Status]

link:%console_url%/k8s/ns/%project_namespace%/events[Events]

link:%console_url%/k8s/ns/%project_namespace%/pods[Pods]

#### Terminal links

link:%terminal_url%[Embedded]

link:%terminal_url%/session/1[Session 1]

link:%terminal_url%/session/2[Session 2]
